name: CI Pipeline with Artifacts

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest > result.log; tail -n 10 result.log

    - name: Upload test result as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-result
        path: artifacts/result.log

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes successfully

    steps:
    - name: Download the test result artifact
      uses: actions/download-artifact@v2
      with:
        name: test-result

    - name: Use test result for deployment
      run: |
        cat result.log
        echo "Deploying application..."
