name: Sequential Workflow Example

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies for Job 1
        run: |
          echo "Installing dependencies for Job 1"
          # Add your installation commands for Job 1

      - name: Run Job 1 task
        run: |
          echo "Running Job 1 tasks"
          # Add your commands to run tests, builds, etc. for Job 1

  job2:
    runs-on: ubuntu-latest
    needs: job1  # job2 depends on job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies for Job 2
        run: |
          echo "Installing dependencies for Job 2"
          # Add your installation commands for Job 2

      - name: Run Job 2 task
        run: |
          echo "Running Job 2 tasks"
          # Add your commands to run tests, builds, etc. for Job 2

  job3:
    runs-on: ubuntu-latest
    needs: job2  # job3 depends on job2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies for Job 3
        run: |
          echo "Installing dependencies for Job 3"
          # Add your installation commands for Job 3

      - name: Run Job 3 task
        run: |
          echo "Running Job 3 tasks"
          # Add your commands to run tests, builds, etc. for Job 3
